stages:
  Split_data:
    cmd: python src/data/split.py
    deps:
    - data/raw_data/raw
    - src/data/split.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize_data:
    cmd: python src/data/normalize.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch_model:
    cmd: python src/data/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/data/grid_search.py
    outs:
    - models/best_params.joblib
