stages:
  Split_data:
    cmd: python src/data/split.py
    deps:
    - data/raw_data/raw
    - src/data/split.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
